# Sets the number of worker processes (usually 1 per core is fine for simple serving)
worker_processes  auto;

events {
    # Sets the maximum number of simultaneous connections that can be opened by a worker process
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    # Speed up transfer rates
    sendfile        on;

    # Enable Gzip compression (good for Angular assets)
    gzip            on;
    gzip_types      text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

    server {
        # NGINX listens on port 80 (as exposed in your Dockerfile)
        listen 80;

        location / {
            root   /usr/share/nginx/html;
            index  index.html;
            try_files $uri $uri/ /index.html;
        }

        location = /index.html {
          root   /usr/share/nginx/html;  # ← ADD THIS LINE
          add_header Cache-Control "no-cache, no-store, must-revalidate";
        }
    }
}
